import type { MDXComponents } from "mdx/types";
import {
  TheoryBox,
  TeacherNote,
  ForStudents,
  ForParents,
  Sources,
  KeyTakeaways,
  CommonMisconception,
  ActionChecklist,
  RelatedConcepts,
  ReflectionPrompt,
  WhyItMatters,
  RelatedGuides,
  WhenToUse,
  Troubleshooting,
  PrintableBlock,
  BookOverview,
  WhoThisIsFor,
  WhatYouWillLearn,
  TopicIntro,
} from "@/components/mdx";

export const mdxComponents: MDXComponents = {
  TheoryBox,
  TeacherNote,
  ForStudents,
  ForParents,
  Sources,
  SourceNote: Sources,
  KeyTakeaways,
  CommonMisconception,
  ActionChecklist,
  RelatedConcepts,
  ReflectionPrompt,
  WhyItMatters,
  RelatedGuides,
  WhenToUse,
  Troubleshooting,
  PrintableBlock,
  BookOverview,
  WhoThisIsFor,
  WhatYouWillLearn,
  TopicIntro,
};
